### ISSUE TITLE
We require good artwork / logo

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1]
For this project we will need a good artwork / logo design.

**Comment by zuuritaly** [comment]
Hello @windelbouwman 
I'm a graphic designer and I design logos for open source projects. I only create logos for projects that have a license, do you have one?

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by windelbouwman** [comment]
Hello @zuuritaly ,

Thanks for reaching out! The license is not yet determined I guess. @shinglyu do you know this? I would suggest a license such as MIT or BSD? Or should be go GPL?

Regards,
Windel

**Comment by shinglyu** [comment]
As for my part (the vm), I used [MIT](https://github.com/RustPython/RustPython/blob/master/vm/LICENSE). If @windelbouwman you are OK with it we can make everything MIT. 

@zuuritaly Thank you so much! I don't have strong opinion about the logo. Since it's something related to Rust and Python, maybe the [Rust gear](https://en.wikipedia.org/wiki/File:Rust_programming_language_black_logo.svg) plus the [python snake](https://www.python.org/community/logos/)? (Not very creative, I admit) Or something creative about metal, iron, rust (oxidation) and snake etc..

**Comment by shinglyu** [comment]
FYI, the Rust community loves metal-related project names. We have Nickel, Iron, stainless, just to name a few.

**Comment by zuuritaly** [comment]
Hello, thanks for the informations, just one question, RustPython is a Python Interpreter written in Rust, what it does, can you tell me that.

Best  Regards

Zuur

**Comment by windelbouwman** [comment]
I am fine with MIT! I think it is a good choice. So RustPython will be the same as normal python, except that "normal" python is also known as CPython, in the sense that python itself was programmed with C. RustPython is a copy, but then implemented in Rust (at least, that is the target). So for a logo, and idea might be a snake which is very rusty, or a rust gear with a snake?

**Comment by shinglyu** [comment]
Or a snake biting its tail, forming a circle which looks like a gear?

**Comment by Tom1380** [comment]
What about a metal snake with cool reflections?

**Comment by shinglyu** [comment]
It needs to look good on stickers and T-shirts, that's the only requirement (?!)

**Comment by windelbouwman** [comment]
How about an old and rusty snake?

**Comment by 42sol-eu** [comment]
Some ideas
