### ISSUE TITLE
Panic in nested exceptions handling

### ISSUE THREAD

**Issue by apatrushev** [RustPython/RustPython#1041]
```python
try:
    {}[1]
except KeyError:
    try:
        raise RuntimeError()
    except RuntimeError:
        pass
```

### expected result
silent and clean process finish

### current result
```
thread 'main' panicked at 'assertion failed: vm.pop_exception().is_some()',
.../.cargo/git/checkouts/rustpython-f8ef4d934ac33cd8/73edde6/vm/src/frame.rs:883:21
```

**Comment by palaviv** [comment]
We have kind of a few problem here that derive from the design I made for the exceptions. when I raise the second exception I pop the exception from the exception stack instead of just copying it as should be. After fixing that we encounter the problem that something need to remove this exception from the stack where if we have nested exception like in this code:
```py
try:
    try:
        raise ZeroDivisionError
    except ZeroDivisionError as ex:
        raise NameError from ex
except NameError as ex2:
    pass
```
the exception will stay in the stack after the code finished.

From what I can see the problem is that we put a `ExceptHandler` block in the block list. When the second exception is raised the original `ExceptHandler` is removed from the block list at `unwind_exception` loop. So when we will try to pop the handler there will be only one.

My point is that the design with the `ExceptHandler` block is not good. I will try to think on something else but please feel free to suggest solutions.
