### ISSUE TITLE
[RFC] Compress bytecode

### ISSUE THREAD

**Issue by windelbouwman** [RustPython/RustPython#1465]
## Summary

We could use gzip like compression on the bytecode to save disk space.

## Detailed Explanation

Right now, we serialize bytecode using the bincode crate. We could use gzip / zlib to compress this data. 

I did a local test and was able to compress sunau.rustpython-01.pyc from 73826 bytes to 10494 bytes using gzip.

Benefits for doing this:
- disk usage reduction.
- We embed some bytecode in the rustpython executable, this would reduce this code size. It might actually speed up startup time of rustpython since we load bytecode as an iterator during startup.

## Drawbacks, Rationale, and Alternatives

Major drawback would be compression / decompression speed.

## Unresolved Questions

- Which compression algorithm is available on all platforms, and has good compression / speed characteristics for this?

**Comment by silmeth** [comment]
If compression/decompression speed is important, it might be a good idea to look at projects like [zram](https://en.wikipedia.org/wiki/Zram) – used to create virtual compressed swap in RAM to compress it – to increase the amount of available memory in a system (I don’t know other projects like that, but probably there are more).

Since such projects are used to compress and decompress currently used RAM they need algorithms with minimal overhead.

I have no experience with profiling compression algorithms myself, but ZRAM uses LZ4 and LZO, so perhaps those are worth looking at?

**Comment by windelbouwman** [comment]
Allrighty, I made a concept in #1491 .

**Comment by sanxiyn** [comment]
Can this be closed?
