### ISSUE TITLE
[RFC] Make a website for RustPython at rustpython.github.io

### ISSUE THREAD

**Issue by coolreader18** [RustPython/RustPython#1715]
## Summary

Create a Github Pages site with information on the project and guides for using or embedding RustPython.

## Detailed Explanation

We currently host our WASM demo on Github Pages, but that's just on `/demo`, we don't use the root of the site for anything currently. I suggest that we could put a sort of landing page for RustPython at `rustpython.github.io/`, with information about the project and links to the project repository, the demo, and the guide. That guide would be for using the RustPython API and could be on `/docs`, maybe built with [mdbook](https://github.com/rust-lang/mdBook), showing solutions for e.g. accepting both ints and floats for a native python function 😉.

## Drawbacks, Rationale, and Alternatives

My rationale is @cedric-h's PR (#1707) and discussions on gitter; it seems that there are a fair amount of people who want to embed RustPython into their Rust project, but are struggling to find good documentation for how to do so.

An alternative would be to just have markdown files in our tree that contain the documentation, but those aren't as pleasant to use and aren't necessarily as discoverable.

## Unresolved Questions

Should the source be all in this repository or in multiple others? (e.g. `RustPython/rustpython.github.io`, `RustPython/docs`; it might be easier to deploy with multiple repositories, given this one's questionable CI situation.)

Related: #1677

**Comment by mireille-raad** [comment]
I would love to work on this issue. I am new to RustPython and as I figure things out, I can leave documentation behind. I can help with writing guides, organize what you have or do the web / front-end development and deployment.

If this repo's CI situation is "questionable", let's start a new one for the site.  Also, you probably don't want to clutter this repo with endless documentation edit and web styling fixes. 

I noticed that most people have the main repo and then the front-end site is separate, for example:
https://github.com/rust-lang/rust
https://github.com/rust-lang/www.rust-lang.org

If you agree on a new repo, then we can move to choose the tooling...

**Comment by coolreader18** [comment]
Great, I'm glad you'd like to help @mireille-raad! I think we'll go with a separate repo, then, unless anyone on the core team would like to object; I'll create that soon and we can start working on it.

**Comment by coolreader18** [comment]
I think the native github pages jekyll themes are good for a blog or just standard website with set pages, but something like mdbook is best for documentation (other than docs.rs, but that can't fit all documentation needs). We could use both; normal github pages for `rustpython.github.io/` and mdbook for `/docs`.

**Comment by coolreader18** [comment]
https://github.com/RustPython/rustpython.github.io

**Comment by mireille-raad** [comment]
I got started on a draft. I am not a designer... so this is like a first take, if you like the general direction, then I can fine tune.

The idea is that there is:
- a minimal menu. 
- An intro or illustration of what the thing.
- How to install (commands for cargo, wapm and conda). There is a link in the footer to each explaining to install them.
- Goals (high level)

I tried to keep the style minimal. I REALLY loved the logo you had and the little hands :D :D so, I tried to re-use them). They give the site personality. I can make the chracters more nuanced if you want me to. 

I added a  background color one time, otherwise the text is too floaty. I used orange (same colors from the hands that someone drew). This makes the site lean toward rust and python when it comes to colors or identity.

I am not sure what other sections you want me to add. I thought this would be a good start. It would be good if i can get some initial reactions on stick to same style or just start over...

----
![landing-page](https://user-images.githubusercontent.com/521705/76255356-6de09180-6224-11ea-866f-724a5e1632a6.png)

**Comment by coolreader18** [comment]
That looks great!! I really like how the font and headings are inspired by rust-lang.org, and I think the overall simplicity combined with the splashes of color gives it a really nice feel. (Oh, and I was the one that drew the hands on the snakes, I love how you used them!) A section for programs or apps that have used rustpython would be nice, though I'm not sure how many of those there are; if we could find enough then maybe some kind of display for those would be cool.

**Comment by mireille-raad** [comment]
Awww.... that logo is very cute 😄 After I am done with this issue, I am going to  use the image of the snakes instead of a turtle in a logo python game.

You are right about rust-lang. Well spotted... I tried to have something in the spirit of rust :). I had the highlight for the title section and as i was looking at it, i was like hmm... i can add the little hands :) 

I added the sections for programs and apps.... and another for "talks/videos"

I also made another more dull/classic option, in case people don't like how the hands as much as i do ;p

![rustpython](https://user-images.githubusercontent.com/521705/76269636-d8a3c400-6248-11ea-89e8-acfacf28165a.png)

**Comment by palaviv** [comment]
Just wanted to say this looks amazing :1st_place_medal:

**Comment by mireille-raad** [comment]
Here is a link to a demo/test site 

- home: https://mireille-raad.github.io/rustpython.github.io/
- blog: https://mireille-raad.github.io/rustpython.github.io/blog
- single post:  https://mireille-raad.github.io/rustpython.github.io/featured/2020/03/11/use-cases.html

@coolreader18 will take care of the deployment and managing another repo for this.

@palaviv -- we will need someone to help with the content. I just put placeholder text.

Tell me if there are suggestions. I tried to test as much as possible on mobile and ipad. We will be fine-tuning :)

**Comment by mireille-raad** [comment]
should we consider this done and close the issue?

**Comment by coolreader18** [comment]
Yep, sounds good. Further development can take place in the rustpython.github.io repo itself.
