### ISSUE TITLE
print to sys.stderr not working on Windows

### ISSUE THREAD

**Issue by palaviv** [RustPython/RustPython#1753]
```py
print("Error", file=sys.stderr)
```
Currently causes the following error:
```py
Traceback (most recent call last):
  File "D:\a\RustPython\RustPython\tests\snippets\printing.py", line 19, in <module>
    print("Error", file=sys.stderr)
OSError: The handle is invalid. (os error 6)
```

**Comment by coolreader18** [comment]
I think the issue is that we treat filenos as Handles (a specifically windows concept, e.g. `FromRawHandle::from_raw_handle`, represented as `void*` but are really just ) instead of as file descriptors (ints that are returned from `open()`, passed to `read()` etc), because `std::fs::File`s are represented as handles on windows, internally.
