### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by antonromanov1** [RustPython/RustPython#2267]
I tried to compile RustPython on my Fedora 31 and it failed. Steps to reproduce:
$ git clone https://github.com/RustPython/RustPython
$ cd RustPython
$ cargo run --verbose demo.py
![image](https://user-images.githubusercontent.com/18309228/95139846-1d0f2800-0776-11eb-862d-03109d121aeb.png)
![image](https://user-images.githubusercontent.com/18309228/95139878-3021f800-0776-11eb-8b85-26cecb10a408.png)

**Comment by d00z3l** [comment]
Hi @antonromanov1,

You need to update rust: `rustup update`

**Comment by coolreader18** [comment]
Eek, Fedora 31 might not have the latest rust version, if you have rust installed from dnf, you might have to use [rustup](https://rustup.rs) instead

**Comment by antonromanov1** [comment]
I am sorry, I had to update the rustc first. Thank you, now it's compiled

**Comment by DaveAxiom** [comment]
I see the solution is to install a newer version of the Rust Compiler as I'm having the same compilation problem. I don't understand why this project uses an experimental compiler feature. Even if this feature is no longer experimental, why would this project rely on a compiler version that is newer than what's being distributed in the latest of Linux distributions? I have the most current Ubuntu-variant distribution and have [rustc](https://packages.ubuntu.com/focal/rustc) v.1.43 which is documented in the [Readme](https://github.com/RustPython/RustPython/blob/master/README.md) as the minimum version.

The philosophy behind the Rust programming language is to provide the most portability and longevity to source code. I don't find this issue to be community friendly to both Open Source and Linux.

**Comment by d00z3l** [comment]
Hi @DaveAxiom,

I am not a developer on the project (and I am on Windows) but I think you need the latest stable release of Rust which comes out every 6 weeks. The README states that 1.43 was required back in May, the latest stable Rust is now 1.47 (https://github.com/rust-lang/rust/blob/master/RELEASES.md). It seems the problem you are facing is that your Linux distro isn't keeping up with release cadence of Rust as it isn't released as often.

**Comment by coolreader18** [comment]
@DaveAxiom I've been unsure about the MSRV (minimum supported rust version) for this project as well, but I think it makes sense to keep it at the latest stable or maybe a version behind, since we mostly just develop this to use as a binary rather than to be used as a library. If you want to use a more up-to-date Rust compiler, you can look into [`rustup`](https://rustup.rs), which is the recommended way to install Rust. Rust is a [relatively](https://steveklabnik.com/writing/how-often-does-rust-change) fast-moving language, at least compared to the speed of Linux distributions like Ubuntu or Debian, and it's not like we don't use the latest stable for nothing. Even since 1.43, there was a change to allow first-class procedural macros as expressions (e.g. `let code = py_compile!(source = "1+1");`) that previously required a really ugly hack, and also a ton of improvements to allow control flow inside `const fn`s (like `constexpr` from C++). Ultimately, I don't think it's fair to say that the release schedule is not friendly to Open-Source/Linux, since there are many much more stable crates in the ecosystem that keep their MSRVs much older (num-traits supports Rust 1.8 I think!), and also RustPython is not a production-ready project as the README says, so I don't think we should need to support stable environments like Ubuntu/Debian with just their repository packages. (Also, I run Arch Linux and I can get the latest version of Rust just fine from `pacman` 🙃 so it's not really a Linux thing)
