### ISSUE TITLE
Using master version of vm in other crate on Windows

### ISSUE THREAD

**Issue by jhoobergs** [RustPython/RustPython#2547]
Building locally on windows works when I execute `powershell scripts\symlinks-to-hardlinks.ps1`.

But when I want to include the `rustpython-vm` crate in another crate from git (to always have the latest version), I get the errors about Lib not being found etc. Probably because the powershell script is not executed.

My current solution is to clone the repo myself, execute the powershell script and use a local path to `rustpython-vm` in my other crate. 

What do you think should be changed to make windows work without the script? I would be glad to help I someone explains why the script is needed and which other solutions could work.

**Comment by Pebaz** [comment]
This is also my current situation, although I didn't know about the local path trick. Can the powershell invocation be put into a build.rs or something? This is impossible to figure out ostensibly to new users. :/

I think this is more of an issue than it might seem to non Windows users because as of yesterday, I was just simply unable to use this library because I thought it was broken on Windows. That actually wasn't the case, it just has an extra step that is not hooked up so you can't use it like a library on Windows. In the realm of game engines, RustPython could be used to great effect for the scripting engine but on Windows right now it is not possible without custom steps.

I would consider this the most exciting modern rust project in development right now and there are a lot of eyes on it. Can Windows support be prioritized?

**Comment by Pebaz** [comment]
@jhoobergs I was able to depend on my own fork of RustPython after putting the symlink converter script into a `build.rs` file.

[Here](https://github.com/RustPython/RustPython/compare/master...Pebaz:master) are the changes that worked for me.

### Possible Solution To Symlink Problem

Since RustPython is using symlinks to have files exist in multiple places in the project tree, a potential different solution would be to put all the symlink files into their own GitHub repository and then have that be a Git submodule in all of the projects that need it.

This might require a new Git submodule for each nested crate but it should solve the platform incompatibility problem with using an OS feature unique to Unix.

**Comment by Pebaz** [comment]
I just realized it would probably be much easier to just have the `build.rs` script copy over the needed files every time. The current symlink to hard link converter is not idempotent and multiple runs will leave the repo in an unusable state.

Instead of using symlinks, why not copy paste to preserve compatibility between platforms?

**Comment by coolreader18** [comment]
Having the build.rs do that would only work when in the git tree - when rustpython is published to crates.io it wouldn't find the files in the parent directory, while with symlinks `cargo publish` just views the symlink as a normal directory and packages it normally. Also, putting it in `build.rs` would make `vm/Lib` dependent on cargo's caching/incremental compilation, which can be pretty finnicky. I think my idea to fix this is to make the derive macro itself recognize that it's pointed towards a fake symlink on windows, do you think that might work?

**Comment by Pebaz** [comment]
@coolreader18 Ah yes those are good points. I think that would work. I would be especially interested if it removed the need to run the powershell script as that requirement makes it so that you cannot depend on RustPython as a library on Windows.

**Comment by jhoobergs** [comment]
@Pebaz Can you try with `rustpython-vm = { git="https://github.com/jhoobergs/RustPython.git", branch = "coolreader18/fix-windows-symlinks" }`?
