### ISSUE TITLE
Increasing recursion depth without adding frames

### ISSUE THREAD

**Issue by pheki** [RustPython/RustPython#3214]
I'm trying to fix the list test_repr_deep test at [Lib/test/list_tests.py#L65](https://github.com/RustPython/RustPython/blob/c1679d807417aca593debeb019b6c3d48ed8e99a/Lib/test/list_tests.py#L65) and I've realized that the problem is that the recursion depth is currently only the number of frames (which can be seen at [`VirtualMachine::check_recursive_call`](https://github.com/RustPython/RustPython/blob/c1679d807417aca593debeb019b6c3d48ed8e99a/vm/src/vm.rs#L523)), and neither the list's `repr` implementation nor `VirtualMachine::to_repr` adds a frame, basically ignoring the recursion depth.

AFAIK, a frame is only added for actual python code, not for builtins / vm, so I believe the best option would be to add another property to the virtual machine with the current recursion depth, which would incremented / decremented in `with_frame` but could also be changed for recursion outside of the python code.

I'll gladly open a PR with those changes if they're approved.

Note that changing the test to a very deep repr (10000 or so nested lists) will actually result in a Segmentation Fault.

**Comment by DimitrisJim** [comment]
This is another case of #2796. Recursions currently performed purely in Rust won't bump the recursion depth since, as you mention, frames aren't added for it. (this is the reason why a seg fault is the result, `check_recursive_call` just doesn't see the call stack increasing).

We can take the discussion there and, obviously, you're more than welcomed to open a PR for it.
