### ISSUE TITLE
Stop the interpreter 

### ISSUE THREAD

**Issue by 5aitama** [RustPython/RustPython#3379]
Hi, I would like to know if we can stop the vm on runtime and if so how to stop it ? Thanks

**Comment by coolreader18** [comment]
Hm, that's a good idea, and shouldn't be too hard to implement! It should mostly just be hooking into the existing check_signals function to allow custom "signals". The only thing is it might be hard to *fully* stop the vm, since right now all exceptions just bubble up normally, and there could be user code that's doing
```py
while True:
    try:
        while True: pass
    except:
        continue
```
(which is why bare `except:` is considered bad practice)
But otherwise, this should totally work.

**Comment by coolreader18** [comment]
@5aitama LMK if #3399 fits your use case

**Comment by 5aitama** [comment]
@coolreader18 #3399 fit great my case. Thank's !
