### ISSUE TITLE
Pip installation issue on MacOS 12.0.2

### ISSUE THREAD

**Issue by chunkybanana** [RustPython/RustPython#3544]
The error message is quite long, so here's the last bit:

```
SyntaxError: Got error in f-string: Invalid expression: invalid syntax. Got unexpected token ',' at line 408 column 27
        completed_str = f"{completed_ratio:,.{precision}f}"
```

This happens whether I build a version with `ssl` or run `get-pip.py` normally.

**Comment by fanninpm** [comment]
Installing pip used to be part of RustPython's CI suite, but it had to be disabled because pip vendors dependencies that RustPython currently doesn't support. The specific problem that you're running into is solved by #3532, but that by itself won't get pip up and running. (The next step along that journey, by the way, is adding `mmap` to RustPython, tracked in #2059.)
