### ISSUE TITLE
Maybe rename the project?

### ISSUE THREAD

**Issue by sinitcin** [RustPython/RustPython#383]
Why not RPython? Thanks.

**Comment by RonnyPfannschmidt** [comment]
Rpython is already taken by the translation/jit gen toolchain of pypy

**Comment by sinitcin** [comment]
@rossjones Can make it even easier - Rython =) Perhaps many would agree that "RustPython" is cumbersome. Is just a sentence, I do not insist =)

**Comment by Tom1380** [comment]
We can come up with some cool names that are [The Snake and the Crab](https://en.wikipedia.org/wiki/The_Snake_and_the_Crab) references.

**Comment by Tom1380** [comment]
Try reading it and coming up with something maybe, I don't have any good ideas for now.

**Comment by Tom1380** [comment]
Or maybe [Elapidae](https://en.wikipedia.org/wiki/Elapidae), which is a family of venomous snakes _not including the python_, which I think is great, because we want to be 'related' to Python, but still preserve an identity I think. [Anaconda](https://en.wikipedia.org/wiki/Anaconda_(Python_distribution)) and [Cobra](https://en.wikipedia.org/wiki/Cobra_(programming_language)l) are already taken.

**Comment by windelbouwman** [comment]
I initially went for rspython, taking the rust rs extension as a prefix. Not very original, but two characters shorter than rustpython :)

**Comment by OddCoincidence** [comment]
I quite like the name `RustPython`. It feels nicely congruous to `CPython`.

**Comment by theLastOfCats** [comment]
python.rs

**Comment by sinitcin** [comment]
@theLastOfCats It's beautiful.

**Comment by theLastOfCats** [comment]
@sinitcin, unfortunately, it's already in use by Python Srbija.

**Comment by sinitcin** [comment]
@theLastOfCats =(

**Comment by windelbouwman** [comment]
Okay, I will close this issue now. I think we will stay with rustpython for some time.
