### ISSUE TITLE
function.__doc__ is wrong

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#3973]
```python
function f(): pass

print(type(f).__doc__)
```
it prints object's doc in rustpython

**Comment by youknowone** [comment]
we have doc generating system using https://github.com/RustPython/__doc__ and `rustpython-derive`. This is not working very well now. we need to investigate which step missed and fix the doc generation.

**Comment by dvermd** [comment]
One of problem here is that the `function` type is not part of `builtins` and is not retrieved by generate_docs.py

**Comment by youknowone** [comment]
Great! How about starting from add adding a function document generation to the script?

```
def f(): pass

type(f).__doc__  # this is a proper doc
```

**Comment by dvermd** [comment]
I see you merged a PR on the __doc__ repository but I don't see the values for the [manually added builtins subtypes](https://github.com/RustPython/__doc__/blob/main/generate_docs.py#L125) in the `docs.inc.rs` file. 
I think this file was generated from the `RustPython/scripts/generate_docs.py` file instead of the one from the `__doc__` repo.

What do you think of these actions to take:

- [ ] Remove `RustPython/scripts/generate_docs.py` and `RustPython/scripts/docs.inc.rs`
- [ ] Add documentation on how the docs are generated and used through the `rustpython-derive` and `rustpython-doc` crates or make it more visible if already written
- [ ] Add a Readme.md to the `__doc__` repo to explain how to update the `docs.inc.rs` file. For example, which docker python can/should be used to only have the CPython modules in the output file.
- [ ] From there on, adding the doc for function is pretty straightforward

**Comment by youknowone** [comment]
@dvermd you are right. That was my mistake.
I totally agree most of the suggestions. About the docker part, using docker will be good too. But adding `-I` option is enough too.
