### ISSUE TITLE
ssl.SSLError.reason

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4000]
## Feature
ssl.SSLError.reason

## Python Documentation
https://docs.python.org/3/library/ssl.html#ssl.SSLError.reason

**Comment by tgsong827** [comment]
can you assign this to me?

**Comment by tgsong827** [comment]
Is this issue related with the sslError format made by `fn convert_openssl_error()` ?

I found that RustPython's sslError format is different with CPython's.

- RustPython
```
ssl.SSLError: [Errno 136] [x509 certificate routines] no certificate or crl found (ssl.rs:691)
```

- CPython
```
ssl.SSLError: [X509: NO_CERTIFICATE_OR_CRL_FOUND] no certificate or crl found (_ssl.c:4293)
```

CPython is printing lib name and reason name.
RustPython is printing errCode and lib str.

CPython is using `_ssl_data.h` to get the lib name and reason name.
and ``

so I wonder this issue is about it.

**Comment by youknowone** [comment]
The issue is not about messages but absense of the attribute `reason`.
In CPython, `fill_and_set_sslerror` function adds `reason` attribute, while RustPython doesn't do in `convert_openssl_error`.

Maybe having same messages would be better, but we don't count them as incompatibility.
