### ISSUE TITLE
Publishing a `rustpython-parser` fork to crates.io?

### ISSUE THREAD

**Issue by charliermarsh** [RustPython/RustPython#4179]
I'm using RustPython as the underlying parser for [ruff](https://github.com/charliermarsh/ruff), a Python linter written in Rust. ruff uses `rustpython-parser`, but not the interpreter / runtime.

ruff is installable via PyPI, but I'd like to distribute it via cargo (on crates.io) as well. The Git dependency on RustPython (and on my [RustPython fork](https://github.com/charliermarsh/RustPython)) makes that impossible right now. (Installing via GIt has also led to flakiness in CI / builds.)

I'd like to publish my RustPython fork to crates.io to enable installing ruff via cargo, but I wanted to check here before doing so as I'm a big fan of this project (as well as a contributor :)) and wouldn't want to cause any issues. Do the maintainers project have any objection? My plan was to publish as `ruff-rustpython-parser` or ` ruff-parser` or something along those lines though am of course happy to publish under any name.

**Comment by charliermarsh** [comment]
FTR, I initially tried to vendor my fork within ruff (then set the `path` in Cargo.toml) but that's _also_ unsupported by Cargo.

**Comment by lastmjs** [comment]
It would be great to get RustPython back up on crates.io!

**Comment by youknowone** [comment]
seriously, I want to do this soon.

**Comment by fanninpm** [comment]
> seriously, I want to do this soon.

That's why I assigned @coolreader18.

**Comment by youknowone** [comment]
Let me work on it during this coming winter. Recently RustPython is looking like to be used from more serious projects than before. I feel like a nice packaging will be more worth than a few more features now.

**Comment by mendelsshop** [comment]
Hi there, sorry to budge in,

I have a crate [git function history](https://github.com/mendelsshop/git_function_history), which only supported rust until now, but now I will be supporting Python, and a few other languages. I am using RustPython to parse python files, I need to get the end locations of `Located`<`StmtKind`> by getting the `end_location` field on `Located`, which requires using the git dependency of RustPython instead of the version from crate.io. Now I want to publish my new version to crates.io, which as mentioned before is not possible using git dependencies or via path.

**Comment by not-my-profile** [comment]
There already are [6 rustpython crates](https://crates.io/search?q=rustpython) published on crates.io, only that they have not been updated in over 2 years. I think it would make more sense to update these crates rather than forking the project.

Why exactly haven't these crates been updated? What are the exact steps that are needed to publish new versions of them?

**Comment by fanninpm** [comment]
@not-my-profile you need to start pestering @coolreader18 more often, as they're the one with privileges to cut releases on crates.io

**Comment by not-my-profile** [comment]
I don't want to pester anybody. If they don't have the time to cut releases that's fine but if that's the case I am sure that they could give somebody else the necessary privileges to publish releases.

CC: @windelbouwman you also seem to have the owner privileges for these crates.

**Comment by youknowone** [comment]
I am sorry for this to be late. I will start to work on this issue soon. And I promise I will finish it until 24th January in worst case.

**Comment by youknowone** [comment]
Recently we are getting a lot of patches about parsers. So I'd like ask how long it will take to be stablized in short-term.
@harupy @yt2b @andersk and  cc @charliermarsh 
And how about your schedules? I will try to fit in your schedules @mendelsshop @not-my-profile

**Comment by coolreader18** [comment]
Just published rustpython-parser 0.2.0 based off the current main!! I'm so sorry it took so long, I've been really busy as of late :confounded:

**Comment by not-my-profile** [comment]
Thanks! And no worries :)

Unfortunately the docs.rs build appears to be failing for the newly published crate ... I just filed #4436 about that.
