### ISSUE TITLE
Be silent even with no file using stdin

### ISSUE THREAD

**Issue by williamdes** [RustPython/RustPython#4363]
https://github.com/RustPython/RustPython/blob/3660ac20cff4152af3281040b5949eef9667493f/src/lib.rs#L187

```sh
echo -e "import json\njson.dumps(['foo', {'bar': ('baz', None, 1.0, 2)}])" | rustpython -q
```

### Actual

```
Welcome to the magnificent Rust Python 0.1.2 interpreter 😱 🖖
'["foo", {"bar": ["baz", null, 1.0, 2]}]'
```

### Expected

```
'["foo", {"bar": ["baz", null, 1.0, 2]}]'
```

**Comment by DimitrisJim** [comment]
Thanks! Message also gets printed even if `-q` is not passed, i.e we don't check if `stdin` is from a pipe or connected to a terminal. The correct solution involves checking for `-q` and then also checking if `isatty(stdin)`. 

The relevant function in CPython is [`pymain_header`](https://github.com/python/cpython/blob/199507b81a302ea19f93593965b1e5088195a6c5/Modules/main.c#L185).

In addition to this, this shouldn't actually print anything either way, [`PRINT_EXPR`](https://docs.python.org/3/library/dis.html#opcode-PRINT_EXPR) is used during interactive mode so this should only print if entered via `-i` or normally via `rustpython/python` (this should be a separate issue though since the parser injects that opcode I believe).
