### ISSUE TITLE
`eval` doesn't work correctly.

### ISSUE THREAD

**Issue by yt2b** [RustPython/RustPython#4364]
On CPython, `eval` works even if space exists at the beginning of the line.

```
>>> eval("   1")
1
```

But on RustPython, IndentationError occurs.

```
>>>>> eval("   1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndentationError: unexpected indent at line 1 column 4
   1
   ^
```

**Comment by branai** [comment]
Hi, I'd like to take a look at this. @DimitrisJim Could you assign this to me?

**Comment by DimitrisJim** [comment]
@yt2b has been opening issues and sending a PR at the same time so you'd have to get the ok from them! 🙂

**Comment by branai** [comment]
#4365

**Comment by branai** [comment]
Understood! I made a fix I thought it was suitable, but if @yt2b already made a PR it can be used instead.

**Comment by yt2b** [comment]
@branai 
OK! I will leave it for you.

**Comment by DimitrisJim** [comment]
There's another `eval` error if you want to tackle it @yt2b, it involves a custom locals object passed as the `locals` argument that raises something else than `KeyError` (see the final check if `test_eval` of `test_builtins.py`). A slight change of the `LoadNameAny` opcode functionality is required since it currently ignores the possible error when looking up a name in the locals.

**Comment by yt2b** [comment]
@DimitrisJim 
I'll tackle another `eval` error in #4375.
