### ISSUE TITLE
[RFC] Replace memchr dependency with std::slice::fill

### ISSUE THREAD

**Issue by youknowone** [RustPython/RustPython#4481]
## Summary

memchr can be replaced with [std::slice::fill](https://doc.rust-lang.org/std/primitive.slice.html#method.fill)

**Comment by Jhowww** [comment]
Hi @youknowone, I can give it a shot.

**Comment by Jhowww** [comment]
Hi @youknowone and @DimitrisJim, I have looked at the code that uses memchr, but I have no direction how to use [std::slice::fill](https://doc.rust-lang.org/std/primitive.slice.html#method.fill) to replace memchr?
I think that memchr is find a element in the slice and std::slice::fill is change the in the slice to some value.
Seems like I should use position(https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position) or find

, like https://github.com/RustPython/RustPython/blob/61b48f108982d865524f86624a9d5bc2ae3bccef/vm/src/stdlib/io.rs#L1905-L1915
Seem like I should use find instead of [std::slice::fill](https://doc.rust-lang.org/std/primitive.slice.html#method.fill)?

**Comment by youknowone** [comment]
Oh, I am sorry. It's my fault. You are right.

**Comment by youknowone** [comment]
I am sorry. I made the wrong issue. memchr is highly optimized so we can't replace it with std::iter.
I thought it was replacable using newly added std::slice::fill, but it wasn't.
