### ISSUE TITLE
[RFC] Faster BigInt Implement via Malachite?

### ISSUE THREAD

**Issue by qingshi163** [RustPython/RustPython#4797]
## Summary
Currently we are using a num-bigint, a pure rust implement for BigInt support, but at lease now the implement is bit naive especially do not have small int optimize witch is a big deal.

The fastest BigInt implement I know is gmplib witch part of GNU, there is a high-level wrapper https://docs.rs/rug/latest/rug/ witch looks really nice.

## Drawbacks, Rationale, and Alternatives
I am worried about the platform supporting mostly for webassembly, I don't see gmplib has offical support for that. and compiling on Windows seem like depends on MingW.

Otherwise we probably need to have our own implement.

**Comment by DimitrisJim** [comment]
Yes! The small int optimization would be really cool to have.

In general, I think we should prefer options that don't require additional software to be present on the host machine, that's why I was also looking into malachite too. 

@qingshi163 are there any other benefits to using `rug` over something like `malachite`? I can see that `GMP` would be battle hardened and probably be faster than malachite with the downside that it might be troublesome to set up.

**Comment by qingshi163** [comment]
malachite sounds great!
