### ISSUE TITLE
A long string in ast.parse() leads to a segfault

### ISSUE THREAD

**Issue by xiaxinmeng** [RustPython/RustPython#4857]
ast.parse() takes a long string as the argument leading to a segfault.

test.py
```
import ast
x = ast.parse('+chr(33)'*1000000)
```

Crash message: Segmentation fault (core dumped)

Environment:
Ubuntu 18.04
rustpython v0.2.0

**Comment by DimitrisJim** [comment]
Nice, this seems like a variation of #4862. Basically we're creating a deeply nested AST here since the `rhs` of every `BinOp` will be another `BinOp` so it fails while trying to recurse into this.

Both these issues will most likely be solved by the same solution: checks while recursing deeply during the compilation phase (I'm guessing the AST traversal is the cause here but I'd need to check to make sure).

Thanks a lot for reporting and feel free to re-open if you disagree.
