### ISSUE TITLE
Pass rust variables to rust function called from python

### ISSUE THREAD

**Issue by LeviLovie** [RustPython/RustPython#5393]
Hello,
I'm trying to make a modding tool for games with your library to write mods in python. My idea is to declare a rust function accessible in python which is going to change a certain thing in the rust game code. For example add a new object to the screen. I managed to make the rust function, but I could not find how can i pass something from the rust game code into that function, so i can change that by calling a function from python.

## Expected use case

```python
draw_text("Hello, world")
```
```rust
#[pyfunction]
fn draw_text(message: String, vm: &rustpython_vm::VirtualMachine, texts: &Vec<Text>) {
    texts.push_back(Text::new(message));
}
```

I'm sorry to disturb if that is already possible, but I could not find out how. Thank you.

**Comment by miviwi** [comment]
Hi, I think you'll get the idea by looking through some of the examples provided in the repo.

This one demonstrates your exact use case (as far as I can tell):
https://github.com/RustPython/RustPython/blob/main/examples/call_between_rust_and_python.rs

...along with it's companion file:
https://github.com/RustPython/RustPython/blob/main/examples/call_between_rust_and_python.py

Try to look through them (the rest of the parent directory is helpful too) and if you still have more questions then somebody can help you for sure. Thanks!

**Comment by LeviLovie** [comment]
I looked into them before writing the issue, but i still can't change anything outside the function in rust. Because the example just does not show how the call from python to rust can change anything outside of the function. In my case i want to draw some objects to the screen, that means i need to modify the objects vector from the shared function.

**Comment by LeviLovie** [comment]
So like this pseudo code:
```rust
struct Game {
    objects: Vec<>,
    vm: VirtualMachine,
    update_fn: PyFunc,
}
impl Game {
    pub fn new() {
        vm = load_file(PYTHON_FILE);
        vm.execute();

        return Self {
            vec![],
            vm,
            vm.get_func(update),
        }
    }

    pub fn run(&self) {
        vm.register_func(|object_x: u32| {
            self.objects.push(Object {object_x, 10, 100, 100});
        })

        while !should_close!() {
            for object in self.objects {
                draw(object);
            }
        }
    }
}
```

**Comment by miviwi** [comment]
Oh... I think I get you; well - first of all - you're gonna want a `#[pyclass]`, for the sake of discussion let's say `Renderer` is one such type, with:
  - a `Renderer::circle(x: f32, y: f32, r: f32)` method,
  - and - somwhere - an instance `let renderer: Renderer = /* ... */`

Now, because it's a `#[pyclass]` that means it implements `ToPyObject` (though I can *vaguely* recall being able to have one where that's not the case... but for the sake of discussion let's ignore it right now), which we can then use like so:
```rust
// Just as a prelude: the type which encapsulates a Python interpreter is `vm::Interpreter`,
// not `vm::VirtualMachine` - this is an object only made available to you if you're *currently*
// executing a piece of Python code.
// So I'll just pretend you have access to a member `interp: vm::Interpreter` instead of `vm` directly

let vm_scope = interp.enter(|vm| {
    let vm_scope = vm.new_scope_with_builtins();   // You'll have to store this object somwhere

    // This will - upon success - expose the `Renderer` as a Python global variable
    vm_scope.globals.set_item("renderer", renderer.clone().to_pyobject(vm), vm)?;
    
    PyResult::Ok(vm_scope);  // <-here we "return" a value from the VM,
                                                 //     which can be of any type we wish
}).expect("failed to set `renderer` global variable!");
```

From this point on, any methods which take a `Scope` in order to execute code - like `VirtualMachine::run_block_expr()`-  will have access to that `Renderer`;

So now let's call one of it's methods!
```rust
interp.enter(|vm|  {    
    vm.run_block_expr(vm_scope, r#"
renderer.circle(100.0, 100.0, 32.0)  # This will call [`Renderer::circle()`] - method from the `#[pyclass]`
    "#);
});
```

...as mentioned in the comment up above: we've managed to call a method on a "remote" type (`Renderer`)
from a piece of python code.
However this is only the beginning. I've cut down on many details, so the reply could be shorter to get the gist
across to you better (I hope), it could be the case that now you'll have even more questions than anwsers, but...
hopefully this makes for at least a starting point for you?
-------------------------------------------------------------------------------------------------------------

##### Small addendum to all this: I've copy-pasted this code into an editor to make sure the LSP doesn't scold me, but haven't compiled it; treat it more as a Proof-of-concept than a working example

**Comment by LeviLovie** [comment]
Alright, thank you very much

**Comment by miviwi** [comment]
if you need more help I'll be glad to share what I know over Discord DMs for ex.; I'm no expert like @youknowone but with the "simpler" (😅) matters I can help for sure

**Comment by LeviLovie** [comment]
Also, I saw `renderer.clone()`, is my change from python gonna affect the original rust structure, so I can render it from rust, even tho it was cloned?

**Comment by miviwi** [comment]
You'll need some kind of reference counting - [`ToPyObject::to_pyobject()`](https://docs.rs/rustpython-vm/latest/rustpython_vm/convert/trait.ToPyObject.html#tymethod.to_pyobject) consumes it's receiver; you can't just have borrows on one object

**Comment by miviwi** [comment]
uh... I've been typing up some kind of elaboration on what I mean by "some kind of reference counting", but the reply has been getting longer and longer (with more and more "holes" too) and beside - it's not strictly related to RustPython itself anyways - so hit me up with a DM if you need more explanation.

**Comment by LeviLovie** [comment]
Ok, I'm gonna try to do that and message you on discord if anything.

**Comment by miviwi** [comment]
I'm `Bruner` over on the server - same profile pic; hopefully you'll be able to find me
