### ISSUE TITLE
memory leak in "any"

### ISSUE THREAD

**Issue by andrew-ld** [RustPython/RustPython#639]
```
def anything(*_):
 pass

class Test:
 def __iter__(self):
   while True:
    yield 1

any(map(anything, Test()))
```

![plot](https://user-images.githubusercontent.com/43882924/54070422-35e4ee00-4260-11e9-9e2e-2095a22cf0b1.png)

**for create process usage stats graph:**
> `psrecord $(pgrep rustpython) --interval 1 --duration 60 --plot plot.png`

**Comment by coolreader18** [comment]
This happens specifically because of how `builtin_any()` is implemented -- it calls `vm.extract_elements()`, which tries to put everything into a Vec before returning it, when it should really just iterate normally. This should be a fairly easy fix: just change `builtin_any()` in `vm/src/builtins.rs` to use `objiter::get_iter()` and then `PyIterable::try_from_object()`.

**Comment by andrew-ld** [comment]
![plot](https://user-images.githubusercontent.com/43882924/54473834-663b0800-47dd-11e9-91d5-c93dcc551fb3.png)
